lonn plugins
CommunalHelper/IsaGrabBag pull request #2
Opened 2022-10-16 20:09 UTC by Mnstrman06

TODO: arrow bubble texture support

2022-10-17 07:24 UTC, catapillie requested changes
Please use `en_gb.lang` to give name to placements.

For example, let's say you are working on the `isaBag/arrowBubble` plugin. You have a placement for each direction, up, down, left and right. Instead of hardcoding the "human-readable" placements names into the plugin's code, give them a simple name like `"left"` for the left placements, `"down"` for the down one, etc... you get the idea.

You'll then want to associate these placement names to an actual readable name using the language file. So, in our example, it would be something like:
```txt
entities.isaBag/arrowBubble.placements.name.up=Arrow Bubble (Up)
entities.isaBag/arrowBubble.placements.name.down=Arrow Bubble (Down)
entities.isaBag/arrowBubble.placements.name.left=Arrow Bubble (Left)
entities.isaBag/arrowBubble.placements.name.right=Arrow Bubble (Right)
```

You don't need to mention `IsaGrabBag` in the placements names. Lönn will add it itself, given you defined the name in the language file. For example, in this case, it'd be:
```txt
mods.IsaGrabBag.name=Isa's Grab Bag
```
(Or, you know, you get to format it the way you want. I also like to put this at the top of the language file.)

2022-10-17 07:24 UTC, catapillie commented on Loenn/lang/en_gb.lang
> +mods.EverestYamlName.name=IsaGrabBag
You probably forgot to change `EverestYamlName`, which is supposed to match the mod's `everest.yaml` name. Whatever you write after the equal sign is what is shown in Lönn.
```suggestion
mods.IsaGrabBag.name=Isa's Grab Bag
```

2022-10-17 19:42 UTC, bigkahuna443 requested changes
Overall notes:
1. Please test plugins in-editor before making a PR, would've caught a lot of these.
2. Missing plugins for the Arrow Block, Corner Boost Block, and the Force Variant Trigger, not sure if you intended to add them or forgot. The latter two should not get placements but still need plugins

2022-10-17 19:42 UTC, bigkahuna443 commented on Loenn/entities/arrowBubble.lua
> +#TODO: add texture based on direction
all the images are formatted as `booster{dir}00.png`, so you can use something like this:
`local texture = "isafriend/objects/booster/booster" .. dir .. "00"`

2022-10-17 19:42 UTC, bigkahuna443 commented on Loenn/entities/arrowBubble.lua
> +        name = "Arrow Bubble (Left, IsaGrabBag)",
to follow up on catapillie's comment, you would change this line to be `name = "left"` and then have `[...]placements.name.left = "Arrow Bubble (Left)"` in the en_gb.lang. check out some of the other legacy loenn plugin repos (or vanilla) for examples

2022-10-17 19:42 UTC, bigkahuna443 commented on Loenn/entities/arrowBubble.lua
> +            direction = left
This doesn't load lol, looks like it's WIP though. I'd recommend making the `direction` field a non-editable dropdown with the directions. Looks like the code needs it to be lowercase which is annoying, I think there's a way to make it display separately though

2022-10-17 19:42 UTC, bigkahuna443 commented on Loenn/entities/rewind.lua
> +    oneUse = true
should be in a `data` table

2022-10-17 19:42 UTC, bigkahuna443 commented on Loenn/entities/waterBoost.lua
> +    boostEnabled = true
should be in a `data` table

2022-10-17 19:42 UTC, bigkahuna443 commented on Loenn/entities/zipline.lua
> +    useStamina = true
should be in a `data` table

2022-10-17 19:42 UTC, bigkahuna443 commented on Loenn/triggers/coreWindTrigger.lua
> +            "None",
use the `wind_patterns` enum for these

2022-10-17 19:42 UTC, bigkahuna443 commented on Loenn/lang/en_gb.lang
> +entities.isaBag/arrowBubble.placements.name.default=arrow Bubble
please use consistent capitalization for these lol. so "arrow Bubble" -> "Arrow Bubble"

2022-10-17 19:42 UTC, bigkahuna443 commented on Loenn/entities/zipline.lua
> +zipline.nodeLineRenderType = "fan"
not sure what these choices are for nodes. use `{0, 2}` for limits, and it should be rendering the actual line like in the ahorn plugin

2023-01-10 14:22 UTC, catapillie commented
Is this still being worked on? I'm willing to review the code, and possibly improve the ports if necessary.

2023-01-10 20:05 UTC, Mnstrman06 commented
The ports are not finished, the remaining functions are things outside of my very limited skillset.

2024-09-08 18:11 UTC, closed without merging